---
require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - lib/generators/**/*.rb
    - gemfiles/*
    - spec/**/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 130
  Exclude:
    - remotipart.gemspec

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false
