---
require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*
    - lib/generators/**/*.rb

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

##########
# LAYOUT #
##########

Layout/LineLength:
  Max: 130
  Exclude:
    - remotipart.gemspec
    - spec/remotipart/features/comments_spec.rb

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

##########
# NAMING #
##########

Naming/BlockForwarding:
  Enabled: false

#########
# RSPEC #
#########

RSpec/MetadataStyle:
  EnforcedStyle: hash

RSpec/ExampleLength:
  Exclude:
    - spec/remotipart/features/comments_spec.rb

RSpec/MultipleExpectations:
  Max: 9

RSpec/NotToNot:
  EnforcedStyle: to_not

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: strict
