language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
before_install:
  - gem update --system
  - gem install bundler --no-document
addons:
  chrome: stable
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
